version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: techrodeo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - techrodeo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  techrodeo-crm-be:
    image: adamsz1/techrodeo-crm-be
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/techrodeo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - techrodeo-network

  techrodeo-crm-bff:
    image: adamsz1/techrodeo-crm-bff
    environment:
      BACKEND_URL: http://techrodeo.hu/v1
    ports:
      - "8085:8085"
    depends_on:
      - techrodeo-crm-be
    networks:
      - techrodeo-network

networks:
  techrodeo-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
